### ISSUE TITLE
Sleepy Demo-FTD do not become Router

### ISSUE THREAD

**Issue by rohithanayady** [openthread/ot-efr32#125]
I have created a Thread network with Border Router as leader(rcp). Then flashed the sleepy-demo-ftd (hard cored the Thread network as created by the leader)code.  The sleepy demo ftd joined as a child, but it still remains as child. After the specified time of 3 min it is still Child. What will be the reason for sleepy-demo-ftd do not become a router and still it is Child(I have searched on this, but didnot get the answer)- the device used is EFR32MG12

**Comment by lmnotran** [comment]
Hi @rohithanayady ,

I'm unable to test using a border router as the leader right now, but I was able to test using a node running `ot-cli-ftd` as the leader. With this setup, I was able to observe the `sleepy-demo-ftd` node upgrade to a router.

I will see if I'm able to get someone from my team to test using a Border Router.

<img width="1207" alt="Screen Shot 2021-08-18 at 1 04 47 PM" src="https://user-images.githubusercontent.com/2881693/129943484-3e8c011e-6619-4f2c-96b7-3320c8920edd.png">

### Hardware
- 2x EFR32MG12 (brd4161a)

### Test setup
1. Flash `ot-cli-ftd` to one efr32mg12
2. Set it up with the sleepy-demo network info

```
> dataset channel 15
Done
> dataset panid 0x2222
Done
> dataset extpanid C0DE1AB5C0DE1AB5
Done
> dataset networkkey 1234C0DE1AB51234C0DE1AB51234C0DE
Done
> dataset networkname SleepyEFR32
Done
> dataset commit active
Done
> ifconfig up
Done
> thread start
Done
>
> state
leader
Done
>
```

3. Flash `sleepy-demo-ftd` to the second efr32mg12
4. Wait some time
5. Check the state of the `sleepy-demo-ftd` node

**Comment by jwhui** [comment]
Closing stale issue.
