### ISSUE TITLE
Broken OT 1.2 support in openthread/ot-efr32

### ISSUE THREAD

**Issue by George-Stefan** [openthread/ot-efr32#137]
I reviewed the latest radio.c from ot-efr32 (https://github.com/openthread/ot-efr32/blob/main/src/src/radio.c).

It looks like the Enh-ACK doesn't get to be encrypted because
txCurrentPacket() doesn't call radioProcessTransmitSecurity() as is expected by writeIeee802154EnhancedAck().

Since openthread/ot-efr32@d3b94c0#diff-5e9808c35ace5ab51673c2a099131b5480e0220c41bcc1ccdf5141ef5a3e25e3

**Comment by romacdon** [comment]
Hi @George-Stefan - Thanks for reporting this. We are aware of issues with both CSL and enhanced acks and are currently working on resolutions.  We'll update this issue went fixes have been pushed.  Thanks again.

**Comment by romacdon** [comment]
Hi @George-Stefan -changes were pushed to the repo yesterday to bring in support for the latest Silabs GSDK (4.1) which also brings in fixes to CSL and enhanced ack processing.  This should address the issues you were having.  Please reach out if you continue to have issues after upgrading.
