### ISSUE TITLE
rcp version is not openthread stack version

### ISSUE THREAD

**Issue by HeFeng1947** [openthread/ot-efr32#229]
The current RCP firmware version queried by otbr-posix command is the commit of ot-efr32 project, not the openthread protocol stack version. This resulted in an inability to match the otbr-posix version, while the ot-nrf528XX project was the same.

**Is openThread clearly defined at this point?**

If we want to write to the OpenThread stack version, only need to mask a few lines of the CMAKE file.
Here is my patch
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2314092..db201ea 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -29,14 +29,14 @@
 cmake_minimum_required(VERSION 3.10.2)
 project(ot-efr32 VERSION 0.2.0)
 
-include("${PROJECT_SOURCE_DIR}/openthread/etc/cmake/functions.cmake")
+# include("${PROJECT_SOURCE_DIR}/openthread/etc/cmake/functions.cmake")
 
-set(OT_PACKAGE_VERSION "" CACHE STRING "OpenThread Package Version")
-if(OT_PACKAGE_VERSION STREQUAL "")
-    ot_git_version(OT_PACKAGE_VERSION)
-    message(STATUS "Setting default package version: ${OT_PACKAGE_VERSION}")
-endif()
-message(STATUS "Package Version: ${OT_PACKAGE_VERSION}")
+# set(OT_PACKAGE_VERSION "" CACHE STRING "OpenThread Package Version")
+# if(OT_PACKAGE_VERSION STREQUAL "")
+#     ot_git_version(OT_PACKAGE_VERSION)
+#     message(STATUS "Setting default package version: ${OT_PACKAGE_VERSION}")
+# endif()
+# message(STATUS "Package Version: ${OT_PACKAGE_VERSION}")
 
 set(EFR32_PLATFORM_VALUES
     "efr32mg1"
```

**Comment by jwhui** [comment]
@HeFeng1947 , the current behavior is expected and was implemented with #115. This change was implemented in response to https://github.com/openthread/ot-nxp/issues/44.

Since, `openthread/opentrhead` is included as a submodule, you should be able to map from `openthread/ot-efr32` commit to `openthread/openthread` commit.

**Comment by HeFeng1947** [comment]
> @HeFeng1947 , the current behavior is expected and was implemented with #115. This change was implemented in response to [openthread/ot-nxp#44](https://github.com/openthread/ot-nxp/issues/44).
> 
> Since, `openthread/opentrhead` is included as a submodule, you should be able to map from `openthread/ot-efr32` commit to `openthread/openthread` commit.

I understand the logic of the current provision, but considering that there is no direct correspondence with otbr-posix version, would you consider adding the protocol stack version in the version information?

**Comment by jwhui** [comment]
> I understand the logic of the current provision, but considering that there is no direct correspondence with otbr-posix version, would you consider adding the protocol stack version in the version information?

@HeFeng1947 , the primary concern I have is that the `openthread/openthread` git hash does not provide any information about the `openthread/ot-efr32` repo. In other words, more than one commit in `openthread/ot-efr32` can map to the same commit in `openthread/openthread`.

**Comment by HeFeng1947** [comment]
> > I understand the logic of the current provision, but considering that there is no direct correspondence with otbr-posix version, would you consider adding the protocol stack version in the version information?
> 
> @HeFeng1947 , the primary concern I have is that the `openthread/openthread` git hash does not provide any information about the `openthread/ot-efr32` repo. In other words, more than one commit in `openthread/ot-efr32` can map to the same commit in `openthread/openthread`.

Yes, I understand your concern. My problem is that the RCP firmware version doesn't match the otbr-posix version, and while we can do a commit mapping table, it doesn't look very elegant. 
Thank you very much for your reply!
