### ISSUE TITLE
Join failed [Security]

### ISSUE THREAD

**Issue by lancersky** [openthread/ot-efr32#331]
Hi Experts,
In my test environment, a Silicon Labs BRD4180A as Commissioner, the firmware built from Simplicity Studio, and the version is
```
> version
SL-OPENTHREAD/2.0.2.0_GitHub-3b79cb0d0; EFR32; Jun 17 2022 19:01:51
Done
```
And a NRF52840 USB dongle as Joiner, the firmware built from https://github.com/openthread/ot-nrf528xx/commit/27a002fbc6abc36974a25666282705c4b73d723c
```
> version
OPENTHREAD/thread-reference-20200818-1510-g3b79cb0d0; NRF52840; Jun 17 2022 14:40:28
Done
```
The two devices are very close together, but the Joiner join failed at last. 
Here is the failed log and sniffer data.
[joining failed.zip](https://github.com/openthread/ot-efr32/files/8926956/joining.failed.zip)

When I try the firmware built from ot-efr32 - https://github.com/openthread/ot-efr32/commit/31e9fc8606d9a68cd79868d2b3169992168a7398, It can Join Success.

**Comment by suveshpratapa** [comment]
Hi @lancersky the trace you attached in [joining failed.zip](https://github.com/openthread/ot-efr32/files/8926956/joining.failed.zip) doesn't seem too helpful, I see the following packet logs:

<img width="1220" alt="Screen Shot 2022-06-23 at 6 04 37 AM" src="https://user-images.githubusercontent.com/66088488/175182885-39df4738-5c43-4b32-a39f-c7c613e78d53.png">

However, I did see reassembly timeout errors.  To resolve these, I would recommend you increase the baud rate on your OTBR.

To change baud rate, you should:
- Add `?uart-baudrate=460800` at the end of the radio URL in `/etc/default/otbr-agent`
The URL should look like so: `spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800`

- You should also rebuild your RCP image with the increased baud rate. Please see the following recommendation in our application note [AN1256: Using the Silicon Labs RCP with the OpenThread Border Router (https://www.silabs.com/documents/public/application-notes/an1256-using-sl-rcp-with-openthread-border-router.pdf): 
<img width="1076" alt="Screen Shot 2022-06-23 at 6 05 50 AM" src="https://user-images.githubusercontent.com/66088488/175182999-931bf940-ff55-4775-a40d-099a06cde3cd.png">

**Comment by romacdon** [comment]
Closing based on proposed baud rate change.
