### ISSUE TITLE
GSDK4.0.2 reply Acknowledgment timeout(more than 0.512ms)

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/ot-efr32#334]
As IEEE 802.15.4-2006 describe, the transmission of an acknowledgment frame shall commence between aTurnaroundTime
and (aTurnaroundTime + aUnitBackoffPeriod) symbols after the reception of the last symbol of the data or
MAC command frame.

O-QPSK symbol rate 62.5Ksymbol/s, a symbol = 0.016ms
aTurnaroundTime = 0.016ms * 12 = 0.192ms
 (aTurnaroundTime + aUnitBackoffPeriod) = 0.016ms * (12 + 20) = 0.512ms

![image](https://user-images.githubusercontent.com/97089879/174937328-c5e5dec2-a465-436e-8aa8-56a5d56a7b05.png)
![image](https://user-images.githubusercontent.com/97089879/174937358-c33ca844-d0ae-4488-96dc-558d7f63b062.png)
![image](https://user-images.githubusercontent.com/97089879/174937568-9af096f9-1491-4531-8ba0-685bfe8fc59b.png)
![image](https://user-images.githubusercontent.com/97089879/174937755-bf1204d2-7daf-424e-81c0-511f656b4aa0.png)
![image](https://user-images.githubusercontent.com/97089879/174938471-607c3792-c450-485c-94bc-02a9c0f2b8ff.png)
[wireshark.zip](https://github.com/openthread/ot-efr32/files/8954211/wireshark.zip)

**Comment by jinpeng1989** [comment]
GSDK3.2.1
![image](https://user-images.githubusercontent.com/97089879/174942292-5e5306b8-1458-4a3f-b758-50e9957f8b15.png)

GSDK4.0.2
![image](https://user-images.githubusercontent.com/97089879/174942138-11083a42-46b7-46e8-bbd4-cf9185c71081.png)

**Comment by suveshpratapa** [comment]
This should be highly improved with our latest GSDK 4.1, and we just recently merged all supporting changes for that GSDK [into `ot-efr32`](https://github.com/openthread/ot-efr32/commit/730b745afb306b5dd62762f1c890be42031deb63).  Please let us know if you can try this with the latest GSDK 4.1.

**Comment by suveshpratapa** [comment]
@lancersky I know you mentioned that changing `timings.rxToTx` to 192 solves this issue for you.  We made a change to increase that value to 256 **_only_** for Thread 1.2 or higher, as we noticed better CSL and link metrics performance with that number. This is for cases like accommodating enhanced ACKs that could be encrypted.

We are now revisiting our change to `timings.rxToTx`
