### ISSUE TITLE
Buillding for the BRD4001A + BRD4308A (MGM210P) Wireless Gecko Module Starter Kit

### ISSUE THREAD

**Issue by puddly** [openthread/ot-efr32#499]
I'm trying to get OT-EFR32 compiled for the Silicon Labs MGM210PA22JIA module on the BRD4001A development kit. Is there an example configuration for this particular board combination?

Everything works perfectly with the BRD4179B daughterboard (EFR32MG21) but it seems like the MGM210P may need some configuration tweaks.  The [MGM210P](https://www.silabs.com/documents/public/data-sheets/mgm210p-datasheet.pdf) is itself based on the EFR32MG21 SoC.

---

Setup steps:

 1. Completely erase each module with Simplicity Commander and perform a blank check.
 2. Compile and flash the `bootloader-uart-xmodem` example in Simplicity Studio (GSDK 4.2.0) for the dev kit. I can confirm the UART bootloader is functional for both modules at this point.
 3. Build the project for each module:

```bash
./script/build --skip-silabs-apps efr32mg21 -DBOARD=BRD4179B
./script/build --skip-silabs-apps efr32mg21 -DBOARD=BRD4308A
```

 4. Flash each module with `commander`.

At this point, `spinel-cli.py` can connect to the EFR32MG21 board just fine at 115200 baud, but the MGM210P is unresponsive. Is some portion of the VCOM USART driver still configured for the EFR32 modules? I would appreciate any help or pointers on where to look to get this combination supported.

Thank you!

**Comment by silabs-sebastien** [comment]
Hi @puddly 

Please note at this time that there is no support for (and no intention to support) using Silabs modules (such as MGM210PA22JIA) with the GitHub repo for OpenThread. You can see list of supported boards in the test script [here](https://github.com/openthread/ot-efr32/blob/main/script/test#L61).

To create projects with OpenThread for Silabs modules you will need to use Simplicity Studio v5 (SSv5). You can obtain your free copy of this software [here](https://www.silabs.com/developers/simplicity-studio).

Sincerely,
