### ISSUE TITLE
Integrate with Slack

### ISSUE THREAD

**Issue by lmnotran** [openthread/ot-efr32#500]
@jwhui Can you add the [Slack GitHub App](https://github.com/apps/slack/) to this repo? I would like to be able to subscribe to this repo in a slack channel

**Comment by lmnotran** [comment]
@jwhui Could you take a look at this please?

**Comment by jwhui** [comment]
@lmnotran , I have installed the Slack GitHub App for this repo. Let me know if you need anything else. Thanks.

**Comment by lmnotran** [comment]
Thanks @jwhui !
