### ISSUE TITLE
[docs] simplicity commander link broken

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-efr32#57]
https://github.com/openthread/ot-efr32/pull/56/checks?check_run_id=2640309338

**Comment by romacdon** [comment]
@lmnotran can you take care of this?  Thanks

**Comment by jwhui** [comment]
@lmnotran @romacdon , the submodule update PRs are currently blocked on this CI check. If you prefer, I can continue to merge the PRs with the understanding that the markdown check is expected to fail. What do you prefer?

**Comment by lmnotran** [comment]
@jwhui Sorry about the delay. Somehow I missed the notification saying I was assigned this issue. I'm working on a fix, but you can go ahead and merge the submodule update PRs even with the failing markdown check. Thanks!
