### ISSUE TITLE
git clone in Dockerfile doesn't have --recursive flag

### ISSUE THREAD

**Issue by 0xlee** [openthread/ot-efr32#665]
Hey,

thanks for your repository. I have some thunderboard sense 2, but the build script wasn't working for me, probably due to some python problems as I'm using arch linux.

Then I tried to use docker image. First building on my own, and then from `siliconlabsinc/ot-efr32-dev:latest`. Both failed with same errors. After digging some time, I found out that the git repository didn't have submodule initialized and cloned.

Would it be ok to add `--recursive` flag on git clone in Dockerfile? That would be great.

Thanks a lot.

**Comment by lmnotran** [comment]
Hi @0xlee ,


Thanks for reaching out! Could you provide a copy-paste of the error? 

We intentionally don't run a recursive submodule init because it would cause the docker image to balloon in size due to the size of `gecko_sdk`.

Best,
Mason

**Comment by 0xlee** [comment]
Thanks for your information.

Then I'll open a new issue for that, because that's an another issue.
