### ISSUE TITLE
OpenThread Sleepy demo doesn't work as expected

### ISSUE THREAD

**Issue by 10andy0** [openthread/ot-efr32#772]
Hi there,

Built it as follows:

```
board="brd4317a"
./script/build $board
```

Flashed sleepy-ftd to one device and sleepy-mtd to another.

On the FTD device, the output was (never saw "sleepy-demo-ftd changed to leader" message as mentioned in the documentation):
`sleepy-demo-ftd started`

after a few seconds, when I typed "child table" command, I could see one child in the table, but when I went and typed state on the MTD device it was in detached state, I could not ping the FTD.

On the MTD device, the output was:
```

sleepy-demo-mtd starting in EM1 (idle) mode
Press Button 0 to toggle between EM1 (idle) and EM2 (sleep) modes
[poll period: 2000 ms.]

state
detached
Done
```

 
How is it possible that on the FTD, there is a child in the table but state is detached on the MTD device? How to communicate in the case?

 
BTW, I tried to press BTN1 on the MTD, followed by pressing BTN1 on the FTD, didn't see any UDP messages printed on the CLI.

 
What did I miss?

gecko_sdk_4.4.0

ot-efr32 (f7cc2e8a94aa30bf47655ce170b0bbe1f832ed49)

Thanks,

Andy

**Comment by lmnotran** [comment]
Hi Andy (@10andy0)! 

Unfortunately, I think I may have inadvertently broken radio communication with my `[sdk] update to GSDK 4.4.0` PR #723 . Please use fc3d5eab7d1e3d1be50a35f02ac7d4735dac497a for the time being. I'm diagnosing what went wrong right now.

Best,
Mason

**Comment by 10andy0** [comment]
Hi Mason (@lmnotran)!,

Thank you for your reply, I tried what you suggested, but got no console output at all from the devices programmed with the images. I built them as follows:
```
git clone https://github.com/openthread/ot-efr32.git
cd ot-efr32
git checkout fc3d5eab7d1e3d1be50a35f02ac7d4735dac497a

git submodule update --init --recursive .
# didn't run ./script/bootstrap as already have all dependencies
board="brd4317a"
./script/build $board
```

Flashed them as follows:
```
./commander flash --serialno=xxxx ot-efr32/build/brd4317a/examples/sleepy-demo-ftd/bin/sleepy-demo-ftd.s37
./commander flash --serialno=yyyy ot-efr32/build/brd4317a/examples/sleepy-demo-mtd/bin/sleepy-demo-mtd.s37
```

No output on the consoles of the devices :(

Cheers,
Andy

**Comment by lmnotran** [comment]
Hey Andy,

Please make sure that you remove the ARM Toolchain version 12 and re-run `script/bootstrap` after checking out fc3d5ea to install version 10.3 as support for GCC 12 was not added until GSDK 4.4.0. This should fix things. If it doesn't, please attach the output of the build command.

Best,
Mason

**Comment by lmnotran** [comment]
Hi @10andy0 !

Were you able to get the sleepy-demo example working?

**Comment by 10andy0** [comment]
Hi  @lmnotran,

   I gave up on this experiment with the old (fc3d5ea) release. I am using SimplicityStudio right now, it works there. Might look at ot-efr32 later when it is stable. 

Thank you

Cheers,
Andrii

**Comment by lmnotran** [comment]
I'm glad to hear you were able to get things working with Simplicity Studio! As of https://github.com/openthread/ot-efr32/pull/776, ot-efr32 is stable again, so you should be able to try the sleepy demo apps again. If you run into issues again, please feel free to reopen this issue. Thanks!
